FROM node:22-bookworm-slim

RUN apt-get update \
  && apt-get install -y --no-install-recommends ffmpeg procps curl \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /home/node/app

USER node

CMD ["node", "dist/worker.main.js"]
